{
 "title": "Heart Disease API - Monitoring",
 "refresh": "5s",
 "panels": [
  {
   "title": "Request Rate (req/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{handler=\"/predict\"}[1m]))",
     "legendFormat": "/predict req/s"
    }
   ]
  },
  {
   "title": "p95 Latency by Endpoint (s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[5m])) by (le, handler))",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Error Rate (5xx) (req/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{status=~\"5..\"}[1m]))",
     "legendFormat": "5xx errors/s"
    }
   ]
  },
  {
   "title": "Total Requests Served",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(http_requests_total{handler=\"/predict\"})",
     "legendFormat": "total /predict calls"
    }
   ]
  }
 ]
}